### PR TITLE
Add support for creating and deleting sections.

### PR DESCRIPTION
**Pull request by jcallaway**
Hi, I'm a developer at the University of Colorado, Boulder.  We are working on a Canvas integration and would like to use your nice Java wrapper around the Canvas API.  This PR adds the ability to add and delete sections to courses, which we will need for our implementation.

### CODE REVIEW

**Comment by kawesome** [comment]
Can one of the admins verify this patch?

**Comment by ToeBee** [comment]
Thanks for the pull request! At first glance, it looks pretty solid to me. I see you used `String.format` in a couple of places for making strings with a placeholder values in them. For some reason I never remember that this exists in Java and end up just concatenating strings together with `+`. Now I just might have to go back and refactor some things...

Anyway, I will let Jenkins do its thing on this PR and give it a closer look and merge it in the next couple of days.

Jenkins: ok to test

**Comment by ToeBee** [comment]
Alright, after poking things a little more, there are a couple of issues here after all.

First of all, the Canvas does not return a `Delete` object when deleting sections. It returns the section object which was just deleted. (Bonus: with no indication that it is now deleted!) This means that your delete method always returns false because Gson tries to parse a Section object into a Delete object so the `getDelete()` method always returns null which gets turned into a false after the map operation. Why does the Canvas API return Delete objects indicating success/failure for some operations and the deleted object for others? Nobody knows.

Also, on the creation method, there is no way to specify the optional `enable_sis_reactivation` option since it is not part of the `Section` object. It could just be added as a 3rd parameter to the create method. Although if any other out-of-object options are added in the future this would break compilation or lead to method overloading. To avoid this, a class could be created in the `requestOptions` package to carry this option. But for a single option this is kind of a lot of overhead so I'm kind of leaning towards just adding a 3rd parameter.

This is not code that you touched but I also just noticed that the `id` field in the `Section` class should probably be a `Long` object, instead of a long primitive. As it stands, it tries to send `"id": 0` in the creation request. If it was an object, it would be null by default instead of 0 so Gson would not serialize it. But it doesn't break Canvas so that's not a big deal. I can swap that before I do the next release.

It looks like our `Session` object is also missing the `restrict_enrollments_to_section_dates` field so that can't be specified during creation either. Probably because it is not returned from GET operation. Actually... that seems like a bug in Canvas. /me goes to open another issue over in [instructure/canvas-lms](https://github.com/instructure/canvas-lms/)

**Comment by jcallaway** [comment]
OK, I modified the creation call to take an enable_sis_reactivation parameter, and the delete call now returns a Sections instead of a boolean.  Please take another look.

**Comment by ToeBee** [comment]
Grr. Our Jenkins bailed out on this build for some reason.

Jenkins: retest this please.

**Comment by ToeBee** [comment]
Grr. Our Jenkins bailed out on this build for some reason.

Jenkins: retest this please.

**Comment by ToeBee** [comment]
The `enable_sis_reactivation` option still isn't actually making it through to the HTTP request being sent to Canvas. But I already have a fix for it so I'm going to go ahead and merge this and fix that plus add the `restrict_enrollments_to_section_dates` field to the Section object since Instructure is already fixing that problem (see instructure/canvas-lms#1095)

Thanks for the contribution!

**Pull request merged**
