### PR TITLE
Throw CanvasException when threshold exceeds Canvas API rate limit.

### PR DESCRIPTION
**Pull request by simmeringc**
Developer @CUBoulder

### CODE REVIEW

**Comment by kawesome** [comment]
Can one of the admins verify this patch?

**Comment by ToeBee** [comment]
Well now I'm curious. Have you managed to actually hit the API rate limit? At one point we tried pretty hard to hit the limit in our test instance to see what actually happens. However we were barely able to put a dent in the rate limit remaining header and it seemed like requests just slowed down the more we sent in parallel. This gave the rate limit more time to recover while requests were being processed. So we pretty much decided we would never hit the limit and as a result, didn't put too much effort into handling this situation. I suspect the calls we were making to the Quiz API just weren't expensive enough and I wondered at the time if there were more expensive calls that would cause the limit to be hit quicker.

However I do have a couple of things on this pull request, regardless of how the rate limit actually works within Canvas:

1) As it stands, your code to throw the exception will not be executed if the limit is actually hit. The [API docs](https://canvas.instructure.com/doc/api/file.throttling.html) say the server will return an HTTP 403 status which means a CanvasException will get thrown right above the code you added, where it checks for any HTTP status that isn't in the 200 range. The intent in this method is to throw more specific exceptions above this code and then if nothing more specific matches, throw a generic `CanvasException` with as much information as possible to let the upstream developer figure out what happened.

2) The [API docs](https://canvas.instructure.com/doc/api/file.throttling.html) say "**If** throttling is applicable to this request ... there will also be a X-Rate-Limit-Remaining header..." This would seem to indicate that some calls may not be subject to throttling and that throttling can be disabled for a given Canvas instance In this case there won't be a `X-Rate-Limit-Remaining` returned which would cause your call to `Double.parseDouble` to throw a `NullPointerException`. 

3) What is the value of 0.1 for the rateLimitThreshold based on? Is it arbitrary or have you actually seen that value being returned when you hit the limit? For us the rate limit starts out at 700 but that might be instance configurable. I'm curious if the error gets thrown if the limit remaining minus the cost of the current call goes below 0 (in which case it might be possible for an error to come back with the limit remaining is > 0.1) or only if the limit is already below 0 when the current call comes in.

4) Lastly, I wonder if this situation would be appropriate for a more specific subclass of `CanvasException`? Like I created the `ObjectNotFoundException` (which extends `CanvasException`) to throw when the API returns a 404. Similarly, this is a very specific error condition where you might want to be able to catch a more specific exception and handle it better - probably by waiting a while and then re-submitting the request. Otherwise you have to fetch the string out of the exception to determine what actually happened.

This is a tough bit of code to work on since reproducing it is so hard. Hmm I suppose I could maybe spin up a docker Canvas instance and try to find the variables to tweak the limits so that it can be reproduced reliably for testing this...

**Comment by simmeringc** [comment]
@ToeBee I pushed a new commit with your changes. You can see the exception get thrown if you set the rate limit equal to the threshold and try to preform an API call through you LMSManager.

**Comment by ToeBee** [comment]
Jenkins: ok to test

**Comment by simmeringc** [comment]
Is this ready to merge?

**Pull request merged**
