### PR TITLE
Int to long pr

### PR DESCRIPTION
**Pull request by cdonnelly1992**
I forgot to open a PR last year apparently so I'm going to open my PR as a continuation of #137  and as a result of the Issue I opened last year (#134). I've gone through and changed pretty much every integer to a long. This is meant to follow the canvas source code saying that all ints in their system are 64bit rather than the 32bit ints that Java uses. Certain things like apiVersion and paging I've left as ints but everything else has been upped to longs. 

First time opening a PR to another project so I hope I did everything correct.

### CODE REVIEW

**Comment by ToeBee** [comment]
I finally make a new release after a year and within hours there is a new PR that breaks compilation on pretty much everything. :) It's all good though. Thanks for the effort.

There are some numbers in here I can't imagine needing to be Longs (such as `CourseSettings.homePageAnnouncementLimit` or `Course.totalStudents`) but... there probably isn't much of a down side to switching. Aside from breaking compilation for everything that depends on this, of course. But that's going to happen regardless even if we only change the fields that definitely need it. 

Since @napsky and @buckett had a conversation about converting things to Long over in #137 I will tag them and see if they have any input on this PR as well.

**Comment by napsky** [comment]
Looks good and as @cdonnelly1992 correctly stated, "the canvas source code saying that all ints in their system are 64bit rather than the 32bit ints that Java uses." Therefore, I personally am ok with updating them all from an integer to a long. In case someone wants to check out the 64bit reference, https://canvas.instructure.com/doc/api/.

**Comment by napsky** [comment]
Also, one of the nice things about a strongly typed and compiled language (in this case Java) is that finding and updating types is not too painful.

**Comment by buckett** [comment]
I think switching to `Long` is the right thing in the long run, maybe with a change like this it would be good to bump the major version? As @napsky says it's easy to spot where changes need to be made but it will cause breaking changes for people. The problems (harder fixes) will come if some application code is storing canvas data somewhere else (eg database) and the field is defined as being an integer there.

**Comment by ToeBee** [comment]
Ok, thank you all for your input. I think I will merge this and follow the suggestion of bumping the major version for this change.

**Pull request merged**
