### PR TITLE
Implemented Submission Reader Methods

### PR DESCRIPTION
**Pull request by dmille83**
Implemented Submission Reader Methods

### CODE REVIEW

**Comment by mpellicer** [comment]
https://github.com/kstateome/canvas-api/pull/113

**Comment by ToeBee** [comment]
@mpellicer how does this look to you? I took your single submission method and included it in here. (And went ahead and added the section one in addition to the course one)

I think the biggest change is: Assignment ID is now an integer instead of a String. I try to stick with strict types if possible. Course/Section IDs can also be passed in as "sis_course_id:1234" so those have to be a String but I don't think assignments can be referenced by SIS ID so it can be the same type as the `Assignment.id` field which is an Integer.

And of course method names changed.

I also realized that there were some type errors in the `Submission` model object and once I corrected those I got some of the include options on the submissions for free.

If this looks good, I will try to get a release put out quickly for you. The other open PRs are mostly pretty simple and I will be merging them shortly.

**Comment by mpellicer** [comment]
@ToeBee Looks good to me, thanks for everything, I'm going to close my PR as incorporated.

**Comment by ToeBee** [comment]
@mpellicer I just released 1.0.22. It may still take a little while to get synced out to the public repos. Note that a change in #111 may require you to change your dependencies slightly or logging could break.

Thanks for your PR!

**Comment by mpellicer** [comment]
Thank you so much @ToeBee! Hope I can contribute more changes in the future.

**Pull request merged**
