### PR TITLE
Switch from using log4j directly to slf4j

### PR DESCRIPTION
**Pull request by buckett**
This allow consumers of the library to pick the logging framework they want to use. If you want all the logging events to go through log4j, just add this as a dependency to the consuming application's pom.xml:
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.27</version>
    </dependency>
```

### CODE REVIEW

**Comment by buckett** [comment]
This fixes #101

**Comment by ToeBee** [comment]
Well this is probably a good change but I wonder how many conflicts it will cause with other PRs :)

However it looks like you missed `CourseSettingsImpl.java` and `GradingStandardImpl.java` when converting classes to slf4j. They throw compilation errors.

**Comment by ToeBee** [comment]
This did break my `TestLauncher.java` class that I run from my IDE when testing new features and PRs:

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation

I will try playing with it some more tomorrow.

**Comment by buckett** [comment]
Sorry about missing those changes, I don't know how I did that. I've fixed them and pushed the changes. I've also merged in master to resolve the conflict.

One way to resolve the `TestLauncher.java` issue, is to use an optional dependency so that the simple implementation of slf4j is there when build/running the project, but when the project is used as a dependency in another project it's not included and that project is free to choose which logging implementation is used.

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by buckett** [comment]
I've committed the possible fix to `TestLauncher` and resolved the conflicts.

**Comment by ToeBee** [comment]
Yep, that does seem to have fixed it. Thanks!

**Pull request merged**
