### PR TITLE
Add code to allow copying courses using Content Migration calls.

### PR DESCRIPTION
**Pull request by RebeccaOxfordUni**

### CODE REVIEW

**Comment by ToeBee** [comment]
Thanks for the pull request! One comment: `ContentMigration.java` being inside of the `model.wrapper` package seems wrong. The wrapper package is for internal use to handle how Canvas returns some of the lists in an inconsistent format. No code that calls the API library should ever need to import the wrapper package. 

And I guess I just created a merge conflict by merging another PR that affected the ApiFactory class. Sorry :)

**Comment by RebeccaOxfordUni** [comment]
Thanks for the feedback Toby, I'll make the changes and do the rebase.

I should have said when I did the PR that I've only covered the API calls to enable one to copy a course, content migration has many other features.

**Comment by ToeBee** [comment]
Yeah, that's fine. I am certainly not insisting on fully fleshed out implementations on everything a PR touches :)

I see you put some other enum options in there for other options but commented them out with a note. That seems reasonable to me. I'll give this a quick run and hopefully merge it shortly.

**Comment by ToeBee** [comment]
Ok so after trying to actually use this code a little, a couple more things. These content migrations seem to be kind of complicated so I'm not entirely sure on some of this. And maybe you were planning for future options? But:
* Why is the `createContentMigration` method taking in a `ContentMigration` object? It doesn't seem to be actually used.
* Should the `createContentMigration` method maybe be renamed to reflect that it is a course specific call? If the rest of the content migration calls ever do get implemented we will need to be able to distinguish between account, course, group and user migration calls. Or was the plan to differentiate via a field in the options class?

But it looks like I was indeed able to create a content migration and it copied a bunch of stuff to a new dummy course I created!

**Comment by RebeccaOxfordUni** [comment]
I've made the changes you suggest Toby, I got rid of the ContentMigration object and changed both the name of the createContentMigration method and the name of the options object as this seems to be how it is done elsewhere in the code.  Do let me know if you would like more changes.

**Comment by ToeBee** [comment]
This seems ok to me. Like I said, it seems like the content migration could get complicated but I guess that's a bridge we will cross when/if we come to it. Thanks!

**Pull request merged**
