### PR TITLE
Various additions

### PR DESCRIPTION
**Pull request by Vulcannis**
Here's a few additions we're using. Adds a few new fields to Course & Role, new action to Sections, and base implementation of the Account Admins interface.

### CODE REVIEW

**Comment by kawesome** [comment]
Can one of the admins verify this patch?

**Comment by ToeBee** [comment]
Jenkins: ok to test

**Comment by ToeBee** [comment]
Thanks for the enhancements! 

Question: how do you get the API to return the `Course.subaccountName` property? I'm not seeing it in the response to the course details API call or in the documentation as an optional include field. It wouldn't surprise me if some other course related call returned it but I am curious where it is hiding.

The use of varargs on the `ListAccountAdminOptions.includes` method is interesting. The existing calls like that in other request options classes take in a list. However a lot of them are enums and end up being called like `includes(Arrays.asList(Enum.OPTION_1))` which would indeed be cleaner for the calling code as varargs since it moves the `asList` call into the library's internal code. The only argument I can see against using varargs is that it won't be consistent with the other existing methods. I'm not opposed to moving towards varargs for these methods. Since it is a compilation breaking change I guess it would have to be done via deprecation and overloading for the existing methods.

And couple of tweaks for the `AccountAdmin` class: It seems to be missing the `user` and `workflow_state` properties. Even though the returned User sub-object does not contain all that many user details, everything returned does seem to map to the existing `User` object so I think you can just drop that in the `AccountAdmin` class with a getter/setter. That way it would be easy to create a list of account admins that includes the user's name without having to make additional API calls to look up the name from the user ID. The workflow_state seems like something that could be an enum but I see it used in a couple different places and no clear docs on all the values it can contain so a String is probably good enough there.

**Comment by Vulcannis** [comment]
It's when you use https://canvas.instructure.com/doc/api/accounts.html#method.accounts.courses_api and include subaccounts, but it's not documented in the include[] for some reason. It is documented for the sort property though, so I assume it's just an oversight. I believe I found it from checking the traffic from the https://community.canvaslms.com/docs/DOC-14284-canvas-production-release-notes-2018-03-10#jive_content_id_Course_and_User_Search feature.

While I did consult other classes, I doubt I gave it any thought. I understand the desire for consistency though, so I'd be fine reverting to the List style. Let me know.

True, I just included the properties I needed. I'll add them in and update the request. An enum would be nice, but without documentation on values it's a bit iffy. Looking at the Canvas source they seem to be just using hard-coded string literals, which isn't the most confidence inspiring thing ever.

**Comment by ToeBee** [comment]
I opened up an issue about the missing documentation with Canvas: instructure/canvas-lms#1273. Their track record of resolving my more challenging API issues isn't great but I think the simple documentation ones have seen a decent response rate.

In the options class, let's stick with the list. I should probably start a list and forming a plan for all the things I want to refactor in version 2.0 - assuming GraphQL doesn't take over and make this library useless before we get around to that :)

**Comment by ToeBee** [comment]
So the issue I opened led to more changes than just documenting the `subaccount` option! They actually left `subaccount` undocumented but added a new `account_name` include option that is documented. And if I am reading this correctly ([link to the commit in question](https://github.com/instructure/canvas-lms/commit/e5d201e1f0a61b05f5e46c43aa2b3e850e232381)), it will return the entire Account object as a nested object in the JSON. But the current (undocumented) behavior will remain and I'm not sure when the new code will make it to a production release so we should probably leave what you have for now. I think I'll just add a comment explaining the situation after I merge this PR.

**Pull request merged**
