### PR TITLE
Support include[]=user on QuizSubmissionReader

### PR DESCRIPTION
**Pull request by wmono**
This allows the relevant user records to be pulled at the same time as quiz submissions, which makes it possible to see who made each submission without making a series of follow-up queries for the users. I had to change the internals of QuizSubmissionImpl a bit so please have a close look in there.

### CODE REVIEW

**Comment by kawesome** [comment]
Can one of the admins verify this patch?

**Comment by ToeBee** [comment]
Apologies, I have been out of the office and on reduced hours for a while due to a bicycle crash and resulting concussion. Hopefully I can give this a good review soon though.

In the meantime... Jenkins: ok to test.

**Comment by ToeBee** [comment]
And then I went and concussed myself. 

The build is failing because of a javadoc error. Java 8 decided to get pretty picky about this. Try a `mvn javadoc:javadoc`

**Comment by ToeBee** [comment]
So I did some tinkering here. The javadoc error was a simple fix. I also added the option to use the `quiz` include option in addition to the `user` one. (9750259dee72a0a03712b054bbf0a928da9569e3) The third option that the API supports is `submission` but I am not sure what kind of object this returns and the API documentation doesn't seem to say so I left that out for now

Providing the User objects in the `QuizSubmissionResponse` object as a map instead of a list is slightly odd but I think I understand the reason. Since Quiz submissions are the primary thing being returned, it allows you to easily look up the user as you iterate through submissions. I think most other places in the Canvas API it returns optional includes as sub-objects instead of a separate list so this is an unusual situation. Although that begs the question of whether to do the same thing for the Quiz. Right now I have it returning a list although I believe you will only ever get a single Quiz object back from this call so it probably doesn't matter in practice.

**Pull request merged**
